"""
model_builder/compiler/postgres.py — Postgres materialized views SQL emitter.

Emits a .sql script that creates SNF views over an existing Postgres table.
Data stays in place. The script is downloaded and run by the user.

Rule: this module emits SQL artifacts only.
It does not touch DuckDB. It does not emit SRF. It does not assert identity.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List

import pandas as pd

from ..config import OUTPUT_DIR


def _quote_ident(name: str) -> str:
    """
    Double-quote a Postgres identifier and escape internal double-quotes.
    Handles column names with spaces, reserved words, and mixed case.
    """
    return '"' + str(name).replace('"', '""') + '"'


def emit_postgres_views(
    df:   pd.DataFrame,
    spec: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Emit a Postgres materialized views SQL script.

    For SQL sources: creates SNF views over the existing table.
    For file sources: creates a new schema with the data as static views.

    Returns { output_path, download_url, entity_count, fact_count, facts_by_dim, warnings }
    """
    mapping     = spec["mapping"]
    lens_id     = spec["lens"]["lens_id"]
    output_name = spec["target"]["output_name"]
    source      = spec["source"]
    schema_name = source.get("schema_name", "public")
    table_name  = source.get("table_name", output_name)
    snf_schema  = f"{output_name}_snf"

    q_schema     = _quote_ident(schema_name)
    q_table      = _quote_ident(table_name)
    q_snf_schema = _quote_ident(snf_schema)

    lines = [
        "-- SNF Materialized Views",
        "-- Generated by Reckoner Model Builder",
        f"-- Dataset: {lens_id}",
        f"-- Source: {schema_name}.{table_name}",
        f"-- Generated: {datetime.utcnow().isoformat()}Z",
        "-- Data stays in place. Run this script. Nothing moves.",
        "",
        f"CREATE SCHEMA IF NOT EXISTS {q_snf_schema};",
        "",
    ]

    # Group mapping by dimension
    dim_cols: Dict[str, List[Dict]] = {d: [] for d in ["WHO", "WHAT", "WHEN", "WHERE", "WHY", "HOW"]}
    for m in mapping:
        dim = m.get("dimension", "").upper()
        if dim in dim_cols:
            dim_cols[dim].append(m)

    # Nucleus expression
    nucleus_spec  = spec["nucleus"]
    nucleus_cols  = nucleus_spec["columns"]
    sep           = nucleus_spec.get("separator", "-")
    pfx           = nucleus_spec.get("prefix", "")
    nucleus_expr  = f" || '{sep}' || ".join(f"{_quote_ident(c)}::VARCHAR" for c in nucleus_cols)
    if pfx:
        nucleus_expr = f"'{pfx}:' || {nucleus_expr}"

    facts_by_dim = {}

    for dim, cols in dim_cols.items():
        if not cols:
            facts_by_dim[dim] = 0
            continue

        table       = f"{q_snf_schema}.{_quote_ident('snf_' + dim.lower())}"
        union_parts = []
        for m in cols:
            col   = m["column"]
            skey  = m["semantic_key"].replace(" ", "_")
            q_col = _quote_ident(col)
            union_parts.append(
                f"    SELECT\n"
                f"        {nucleus_expr} AS entity_id,\n"
                f"        '{dim.lower()}' AS dimension,\n"
                f"        '{skey}' AS semantic_key,\n"
                f"        {q_col}::VARCHAR AS value,\n"
                f"        '{dim.lower()}' || '|' || '{skey}' || '|' || {q_col}::VARCHAR AS coordinate,\n"
                f"        '{lens_id}' AS lens_id,\n"
                f"        '1.0.0' AS translator_version\n"
                f"    FROM {q_schema}.{q_table}\n"
                f"    WHERE {q_col} IS NOT NULL"
            )

        union_sql = "\n    UNION ALL\n".join(union_parts)
        lines += [
            f"CREATE MATERIALIZED VIEW {table} AS",
            union_sql + ";",
            "",
            f"CREATE INDEX ON {table}(coordinate);",
            f"CREATE INDEX ON {table}(entity_id);",
            "",
        ]
        facts_by_dim[dim] = len(cols)

    # snf_hub — display table
    label_col    = next((m["column"] for m in mapping if m["dimension"] == "WHAT"), nucleus_cols[0])
    sublabel_col = next((m["column"] for m in mapping if m["dimension"] == "WHO"), None)
    q_label      = _quote_ident(label_col)
    q_sublabel   = _quote_ident(sublabel_col) if sublabel_col else "NULL"

    lines += [
        f"CREATE MATERIALIZED VIEW {q_snf_schema}.snf_hub AS",
        "    SELECT",
        f"        {nucleus_expr} AS entity_id,",
        f"        {nucleus_expr} AS nucleus,",
        f"        {q_label}::VARCHAR AS label,",
        f"        {q_sublabel}::VARCHAR AS sublabel,",
        f"        '{lens_id}' AS lens_id,",
        "        '1.0.0' AS translator_version",
        f"    FROM {q_schema}.{q_table}",
        f"    WHERE {_quote_ident(nucleus_cols[0])} IS NOT NULL;",
        "",
        f"CREATE INDEX ON {q_snf_schema}.snf_hub(entity_id);",
        "",
    ]

    # snf_affordances
    aff_parts = []
    for dim, cols in dim_cols.items():
        for m in cols:
            col   = m["column"]
            skey  = m["semantic_key"]
            q_col = _quote_ident(col)
            aff_parts.append(
                f"    SELECT '{dim.lower()}' AS dimension, '{skey}' AS field,\n"
                f"           COUNT(DISTINCT {nucleus_expr}) AS distinct_entities,\n"
                f"           COUNT(*) AS fact_count\n"
                f"    FROM {q_schema}.{q_table} WHERE {q_col} IS NOT NULL"
            )

    if aff_parts:
        lines += [
            f"CREATE MATERIALIZED VIEW {q_snf_schema}.snf_affordances AS",
            "\n    UNION ALL\n".join(aff_parts) + ";",
            "",
        ]

    # Refresh script
    lines += [
        "-- refresh.sql — run when source data changes",
        f"-- REFRESH MATERIALIZED VIEW {q_snf_schema}.snf_hub;",
    ] + [
        f"-- REFRESH MATERIALIZED VIEW {q_snf_schema}.{_quote_ident('snf_' + dim.lower())};"
        for dim in ["WHO", "WHAT", "WHEN", "WHERE", "WHY", "HOW"]
        if dim_cols.get(dim)
    ] + [
        f"-- REFRESH MATERIALIZED VIEW {q_snf_schema}.snf_affordances;",
    ]

    sql_content = "\n".join(lines)
    output_path = OUTPUT_DIR / f"{output_name}_snf_views.sql"
    output_path.write_text(sql_content, encoding="utf-8")

    return {
        "output_path":  str(output_path),
        "download_url": f"/api/mb/download/{output_path.name}",
        "entity_count": 0,   # not computable for views path — row count at runtime
        "fact_count":   sum(facts_by_dim.values()),
        "facts_by_dim": facts_by_dim,
        "warnings": [
            "Row and entity counts are not available for the views path — "
            "they depend on the live data in your Postgres table."
        ],
        "lens_id": lens_id,
    }
